services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperStrongPassword123! # замінити пізніше
    ports:
      - "1433:1433" 
    volumes:
      - sql_data:/var/opt/mssql 

  api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: event_reservation_api
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=EventReservationDb;User Id=sa;Password=SuperStrongPassword123!;TrustServerCertificate=True;
    depends_on:
      - db 

volumes:
  sql_data: